# Generated by Django 3.0 on 2019-12-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_aluno_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='usuario',
            new_name='Usuario',
        ),
    ]
